from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 660)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(1000, 660))
        Dialog.setMaximumSize(QtCore.QSize(1000, 660))
        Dialog.setSizeGripEnabled(False)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(510, 10, 481, 281))
        self.groupBox_2.setObjectName("groupBox_2")
        self.rawDataArea = QtWidgets.QWidget(self.groupBox_2)
        self.rawDataArea.setGeometry(QtCore.QRect(10, 30, 461, 241))
        self.rawDataArea.setObjectName("rawDataArea")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 330, 483, 311))
        self.groupBox_3.setStyleSheet("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.MWKnotBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.MWKnotBox.setObjectName("MWKnotBox")
        self.gridLayout.addWidget(self.MWKnotBox, 7, 7, 1, 1)
        self.RSSlider = MySlider2(self.groupBox_3)
        self.RSSlider.setOrientation(QtCore.Qt.Horizontal)
        self.RSSlider.setObjectName("RSSlider")
        self.gridLayout.addWidget(self.RSSlider, 12, 4, 1, 4)
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 5, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.groupBox_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 9, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 14, 5, 1, 1)
        self.nPermBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.nPermBox.setObjectName("nPermBox")
        self.gridLayout.addWidget(self.nPermBox, 4, 4, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 6, 0, 1, 2)
        self.MWSigmaSlider = MySlider1(self.groupBox_3)
        self.MWSigmaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.MWSigmaSlider.setObjectName("MWSigmaSlider")
        self.gridLayout.addWidget(self.MWSigmaSlider, 7, 4, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 7, 0, 2, 1)
        self.AreaLengthSlider = MySlider3(self.groupBox_3)
        self.AreaLengthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.AreaLengthSlider.setObjectName("AreaLengthSlider")
        self.gridLayout.addWidget(self.AreaLengthSlider, 14, 4, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.groupBox_3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 11, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 1, 1, 3)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 12, 1, 1, 2)
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 14, 1, 1, 2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 4, 0, 2, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 10, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.groupBox_3)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 13, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.ScalingSlider = MySlider1(self.groupBox_3)
        self.ScalingSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ScalingSlider.setObjectName("ScalingSlider")
        self.gridLayout.addWidget(self.ScalingSlider, 2, 4, 1, 4)
        self.line_2 = QtWidgets.QFrame(self.groupBox_3)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 2)
        self.TWKnotBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.TWKnotBox.setObjectName("TWKnotBox")
        self.gridLayout.addWidget(self.TWKnotBox, 10, 7, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout.addWidget(self.checkBox_7, 14, 0, 1, 1)
        self.JitteringSlider = MySlider1(self.groupBox_3)
        self.JitteringSlider.setOrientation(QtCore.Qt.Horizontal)
        self.JitteringSlider.setObjectName("JitteringSlider")
        self.gridLayout.addWidget(self.JitteringSlider, 0, 4, 1, 4)
        self.RCNumBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.RCNumBox.setObjectName("RCNumBox")
        self.gridLayout.addWidget(self.RCNumBox, 14, 7, 1, 1)
        self.TWSigmaSlider = MySlider1(self.groupBox_3)
        self.TWSigmaSlider.setOrientation(QtCore.Qt.Horizontal)
        self.TWSigmaSlider.setObjectName("TWSigmaSlider")
        self.gridLayout.addWidget(self.TWSigmaSlider, 10, 4, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 10, 0, 1, 1)
        self.LengthBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.LengthBox.setObjectName("LengthBox")
        self.gridLayout.addWidget(self.LengthBox, 4, 7, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 12, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 10, 5, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(510, 330, 481, 281))
        self.groupBox_4.setObjectName("groupBox_4")
        self.augmentatedArea = QtWidgets.QWidget(self.groupBox_4)
        self.augmentatedArea.setGeometry(QtCore.QRect(10, 30, 461, 241))
        self.augmentatedArea.setObjectName("augmentatedArea")
        self.RawdataPlotButton = QtWidgets.QPushButton(Dialog)
        self.RawdataPlotButton.setGeometry(QtCore.QRect(510, 300, 481, 21))
        self.RawdataPlotButton.setStyleSheet("background-color: rgb(239, 41, 41);")
        self.RawdataPlotButton.setObjectName("RawdataPlotButton")
        self.AugmentatedPlotButton = QtWidgets.QPushButton(Dialog)
        self.AugmentatedPlotButton.setGeometry(QtCore.QRect(510, 620, 481, 21))
        self.AugmentatedPlotButton.setStyleSheet("background-color: rgb(114, 159, 207);")
        self.AugmentatedPlotButton.setObjectName("AugmentatedPlotButton")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 481, 311))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 5, 0, 1, 1)
        self.selectFolderBtn = QtWidgets.QPushButton(self.groupBox)
        self.selectFolderBtn.setObjectName("selectFolderBtn")
        self.gridLayout_2.addWidget(self.selectFolderBtn, 7, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 8, 0, 1, 2)
        self.processingSaveBtn = QtWidgets.QPushButton(self.groupBox)
        self.processingSaveBtn.setObjectName("processingSaveBtn")
        self.gridLayout_2.addWidget(self.processingSaveBtn, 7, 1, 1, 1)
        self.processingBtn = QtWidgets.QPushButton(self.groupBox)
        self.processingBtn.setObjectName("processingBtn")
        self.gridLayout_2.addWidget(self.processingBtn, 4, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout.addWidget(self.label_15)
        self.selectChannelCB = QtWidgets.QComboBox(self.groupBox)
        self.selectChannelCB.setObjectName("selectChannelCB")
        self.selectChannelCB.addItem("")
        self.selectChannelCB.addItem("")
        self.selectChannelCB.addItem("")
        self.selectChannelCB.addItem("")
        self.selectChannelCB.addItem("")
        self.selectChannelCB.addItem("")
        self.horizontalLayout.addWidget(self.selectChannelCB)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.selectFileBtn = QtWidgets.QPushButton(self.groupBox)
        self.selectFileBtn.setObjectName("selectFileBtn")
        self.gridLayout_2.addWidget(self.selectFileBtn, 4, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.groupBox)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout_2.addWidget(self.line_9, 3, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.groupBox)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_2.addWidget(self.line_8, 6, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.groupBox)
        self.line_7.setGeometry(QtCore.QRect(10, 60, 118, 3))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")

        self.retranslateUi(Dialog)
        self.selectFileBtn.clicked.connect(Dialog.select_file)
        self.selectFolderBtn.clicked.connect(Dialog.select_folder)
        self.checkBox.toggled['bool'].connect(Dialog.jittering)
        self.checkBox_2.toggled['bool'].connect(Dialog.scaling)
        self.checkBox_3.toggled['bool'].connect(Dialog.permutation)
        self.checkBox_4.toggled['bool'].connect(Dialog.magnitudewarping)
        self.checkBox_5.toggled['bool'].connect(Dialog.timewarping)
        self.checkBox_6.toggled['bool'].connect(Dialog.randomsampling)
        self.checkBox_7.toggled['bool'].connect(Dialog.randomcutout)
        self.RawdataPlotButton.clicked.connect(Dialog.plot_raw)
        self.AugmentatedPlotButton.clicked.connect(Dialog.plot_aug)
        self.processingSaveBtn.clicked.connect(Dialog.process_save)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Data Augmentation Tool For Sensor Data"))
        self.groupBox_2.setTitle(_translate("Dialog", "Raw data"))
        self.groupBox_3.setTitle(_translate("Dialog", "Augmentation Methods"))
        self.label_6.setText(_translate("Dialog", "knot:"))
        self.label_4.setText(_translate("Dialog", "Length:"))
        self.label_10.setText(_translate("Dialog", "num:"))
        self.checkBox_4.setText(_translate("Dialog", "MagnitudeWarping"))
        self.checkBox_2.setText(_translate("Dialog", "Scaling"))
        self.label.setText(_translate("Dialog", "scaling factor:"))
        self.label_9.setText(_translate("Dialog", "nSample:"))
        self.label_11.setText(_translate("Dialog", "area length"))
        self.checkBox_3.setText(_translate("Dialog", "Permutation"))
        self.label_8.setText(_translate("Dialog", "sigma:"))
        self.label_2.setText(_translate("Dialog", "SNR:"))
        self.checkBox_7.setText(_translate("Dialog", "RandomCutout"))
        self.checkBox_5.setText(_translate("Dialog", "TimeWarping"))
        self.label_5.setText(_translate("Dialog", "sigma:"))
        self.checkBox_6.setText(_translate("Dialog", "RandomSampling"))
        self.label_7.setText(_translate("Dialog", "knot:"))
        self.checkBox.setText(_translate("Dialog", "GaussianNoise"))
        self.label_3.setText(_translate("Dialog", "nPerm:"))
        self.groupBox_4.setTitle(_translate("Dialog", "Augmentation data"))
        self.RawdataPlotButton.setText(_translate("Dialog", "Raw data Plot"))
        self.AugmentatedPlotButton.setText(_translate("Dialog", "Augmentated data Plot"))
        self.groupBox.setTitle(_translate("Dialog", "Settings"))
        self.label_17.setText(_translate("Dialog", "Batch Processing"))
        self.selectFolderBtn.setText(_translate("Dialog", "Select Folder"))
        self.processingSaveBtn.setText(_translate("Dialog", "Processing and Save"))
        self.processingBtn.setText(_translate("Dialog", "Processing"))
        self.label_14.setText(_translate("Dialog", "Display mode Setting"))
        self.label_18.setText(_translate("Dialog", "Single Processing"))
        self.label_15.setText(_translate("Dialog", "Select channel:"))
        self.selectChannelCB.setItemText(0, _translate("Dialog", "1"))
        self.selectChannelCB.setItemText(1, _translate("Dialog", "2"))
        self.selectChannelCB.setItemText(2, _translate("Dialog", "3"))
        self.selectChannelCB.setItemText(3, _translate("Dialog", "4"))
        self.selectChannelCB.setItemText(4, _translate("Dialog", "5"))
        self.selectChannelCB.setItemText(5, _translate("Dialog", "6"))
        self.selectFileBtn.setText(_translate("Dialog", "Select File"))

from MySlider import MySlider1, MySlider2, MySlider3


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
